# Generated by Django 2.0.7 on 2018-07-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipout',
            name='sushi',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='tipout',
            name='teppan',
            field=models.CharField(default='', max_length=140),
        ),
    ]
