# Generated by Django 2.0.7 on 2018-08-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20180724_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipout',
            name='bar',
            field=models.CharField(default='', max_length=150),
        ),
    ]
