# Generated by Django 2.0.7 on 2018-08-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_tipout_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipout',
            name='busser',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='tipout',
            name='bar',
            field=models.CharField(default='', max_length=140),
        ),
    ]
