# Generated by Django 2.0.7 on 2018-08-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180731_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipout',
            name='total',
            field=models.CharField(default='', max_length=140),
        ),
    ]
