# Generated by Django 2.1.2 on 2018-12-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_tipout_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipout',
            name='tip',
            field=models.CharField(default='0', max_length=140),
        ),
        migrations.AlterField(
            model_name='tipout',
            name='bar',
            field=models.CharField(default='0', max_length=140),
        ),
        migrations.AlterField(
            model_name='tipout',
            name='busser',
            field=models.CharField(default='0', max_length=140),
        ),
        migrations.AlterField(
            model_name='tipout',
            name='sushi',
            field=models.CharField(default='0', max_length=140),
        ),
        migrations.AlterField(
            model_name='tipout',
            name='teppan',
            field=models.CharField(default='0', max_length=140),
        ),
        migrations.AlterField(
            model_name='tipout',
            name='total',
            field=models.CharField(default='0', max_length=140),
        ),
    ]
