# Generated by Django 2.1.2 on 2019-01-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20181230_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipout',
            name='tip',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
