# Generated by Django 2.1.2 on 2019-01-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20190104_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipout',
            old_name='bar',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='tipout',
            old_name='busser',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='tipout',
            name='sushi',
        ),
        migrations.RemoveField(
            model_name='tipout',
            name='teppan',
        ),
        migrations.RemoveField(
            model_name='tipout',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='tipout',
            name='total',
        ),
    ]
